### ISSUE TITLE
Failed to activate the coffee-compile package

### ISSUE THREAD

**Issue by giano** [adrianlee44/atom-coffee-compile#34]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [coffee-compile](https://github.com/adrianlee44/atom-coffee-compile) package, v0.17.1

### Stack Trace

Failed to activate the coffee-compile package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:449:13)
  at /Users/giano/.atom/packages/coffee-compile/lib/fs-util.coffee:42:29
  at Array.some (native)
  at Object.module.exports.isPathInSrc (/Users/giano/.atom/packages/coffee-compile/lib/fs-util.coffee:41:12)
  at /Users/giano/.atom/packages/coffee-compile/lib/main.coffee:66:32
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:276:9)
  at /Users/giano/.atom/packages/coffee-compile/lib/main.coffee:65:45
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at Object.module.exports.activate (/Users/giano/.atom/packages/coffee-compile/lib/main.coffee:58:17)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:313:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -6:04.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui)
     -5:53.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -5:41.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -5:37.7.0 core:save (atom-text-editor.editor.is-focused)
     -5:17.8.0 core:copy (atom-text-editor.editor.is-focused)
     -5:15.7.0 core:save (atom-text-editor.editor.is-focused)
     -5:08.4.0 core:copy (atom-text-editor.editor.is-focused)
  4x -5:07.4.0 core:paste (atom-text-editor.editor.is-focused)
     -5:03.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:44.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:11.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:02.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:02.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".live-archive"
    ]
  },
  "coffee-compile": {
    "compileOnSave": true,
    "noTopLevelFunctionWrapper": false,
    "compileOnSaveWithoutPreview": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.8
atom-runner, v2.4.1
autocomplete-modules, v1.0.0
coffee-compile, v0.17.1
color-picker, v2.0.11
color-tabs, v0.1.8
color-tabs-regex, v0.2.1
emmet, v2.3.12
flex-tool-bar, v0.4.4
grunt-runner, v0.11.0
language-jade, v0.5.1
language-swift, v0.4.0
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-csslint, v0.0.14
linter-doiuse, v0.2.3
linter-jshint, v1.1.4
linter-jsonlint, v0.1.4
linter-less, v2.0.3
linter-swiftc, v2.0.0
linter-swiftlint, v0.1.0
linter-tidy, v1.0.1
live-archive, v0.1.15
minimap, v4.12.1
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-selection, v4.3.0
monokai, v0.15.0
pigments, v0.9.1
project-manager, v1.15.11
project-view, v0.1.2
regex-railroad-diagram, v0.8.3
remote-edit, v1.8.14
seti-ui, v0.7.1
simple-drag-drop-text, v0.2.3
tool-bar, v0.1.8

# Dev
No dev packages
```

**Comment by giano** [comment]
Sorry, still throwing on 1.17.2.

**Comment by adrianlee44** [comment]
Are you opening a project or a single file?

**Comment by giano** [comment]
Actually a project. Now tried with a new window and it's working when Atom
is focused on a single "non project" file. Any config hack I must apply to
project?

On Tue, Jul 28, 2015 at 8:46 AM, Adrian Lee <notifications@github.com>
wrote:

> Are you opening a project or a single file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adrianlee44/atom-coffee-compile/issues/34#issuecomment-125469634>
> .
>



-- 
Stefano Valicchia

Computers are like air conditioners, they stop working properly if you open
Windows.

**Comment by giano** [comment]
Btw, thanks for this Package, it's life saving. I "grunt compile" the project on run, but having a .js compiled in real time is very convenient.

**Comment by adrianlee44** [comment]
It should work on a project but it seems like there is a bug. The last fix was to fix the single "non project" file case. I'll take another look.

**Comment by giano** [comment]
Thanks!

On Tue, Jul 28, 2015 at 9:07 AM, Adrian Lee <notifications@github.com>
wrote:

> It should work on a project but it seems like there is a bug. The last fix
> was to fix the single "non project" file case. I'll take another look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adrianlee44/atom-coffee-compile/issues/34#issuecomment-125477708>
> .
>



-- 
Stefano Valicchia

Computers are like air conditioners, they stop working properly if you open
Windows.

**Comment by adrianlee44** [comment]
I just bumped coffee-compile to v0.17.3 with a simple check. Before you download the update, can you set source to `.` and cwd to `.` to see if the bug is still showing up?

Thanks!

**Comment by giano** [comment]
Yes, it works that way!

On Tue, Jul 28, 2015 at 9:43 AM, Adrian Lee <notifications@github.com>
wrote:

> I just bumped coffee-compile to v0.17.3 with a simple check. Before you
> download the update, can you set source to . and cwd to . to see if the
> bug is still showing up?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adrianlee44/atom-coffee-compile/issues/34#issuecomment-125485623>
> .
>



-- 
Stefano Valicchia

Computers are like air conditioners, they stop working properly if you open
Windows.
