### ISSUE TITLE
Uncaught TypeError: source.some is not a function

### ISSUE THREAD

**Issue by soncy** [adrianlee44/atom-coffee-compile#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.11
**Thrown From**: [coffee-compile](https://github.com/adrianlee44/atom-coffee-compile) package, v0.18.0

### Stack Trace

Uncaught TypeError: source.some is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: source.some is not a function
  at Object.module.exports.isPathInSrc (/Users/soncy/.atom/packages/coffee-compile/lib/fs-util.coffee:40:12)
  at Object.module.exports.save (/Users/soncy/.atom/packages/coffee-compile/lib/main.coffee:55:49)
  at /Users/soncy/.atom/packages/coffee-compile/lib/main.coffee:30:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:31.2.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
  3x -0:30.5.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:29.2.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
  2x -0:13 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:11.7.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:11 pane:show-next-item (atom-text-editor.editor.is-focused)
  3x -0:08.6.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-eighties-dark-syntax"
    ],
    "disabledPackages": [
      "linter-jshint"
    ]
  },
  "coffee-compile": {
    "cwd": "./src",
    "destination": "./lib",
    "source": [
      "./"
    ],
    "enableProjectConfig": true,
    "compileOnSaveWithoutPreview": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.12
atom-ternjs, v0.7.2
base16-eighties-dark-syntax, v0.1.0
coffee-compile, v0.18.0
file-icons, v1.6.9
highlight-selected, v0.10.1
linter, v1.6.0
linter-coffeelint, v1.1.0
markdown-preview-plus, v2.1.1
terminal-plus, v0.4.3

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
It looks like you have project config enabled. Can you put the configuration here?

**Comment by soncy** [comment]
cwd: './src'
destination: './lib'
source: './'
compileOnSave: true
compileOnSaveWithoutPreview: true


i have project enabled, but it looks like not work, it can't override global coffee-compile configurations.

**Comment by adrianlee44** [comment]
Source should be an array but the current code doesn't check for it. I'll update coffee-compile to check for that. For the meanwhile, can you can source to `['./']` and see if it works?

**Comment by soncy** [comment]
still can't work,if option 'Compile On Save Without Preview' is not checked in global configurations.

**Comment by soncy** [comment]
global configurations
<img width="352" alt="qq20150923-1" src="https://cloud.githubusercontent.com/assets/1466481/10039208/3475655a-6202-11e5-8ed4-d04f0b27220f.png">

project configurations :

cwd: './src'
destination: './lib'
source: ['./']
compileOnSave: true
compileOnSaveWithoutPreview: true

**Comment by adrianlee44** [comment]
Thanks. I'm able to reproduce the bug with `compileOnSaveWithoutPreview`
