### ISSUE TITLE
Compile opens blank atom pane

### ISSUE THREAD

**Issue by liepa** [adrianlee44/atom-coffee-compile#52]
I'm on MacOS High Sierra 10.13.1

Atom 1.23.1

In developer console I can see this error:

Uncaught (in promise) TypeError: Class constructor TextEditor cannot be invoked without 'new'
    at new PreviewEditor (/Users/liepajan/.atom/packages/coffee-compile/lib/preview-editor.coffee:12:5)
    at /Users/liepajan/.atom/packages/coffee-compile/lib/main.coffee:46:7
    at Workspace.createItemForURI (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1324:28)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1130:42)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:449
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:105)
    at Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1308:25)
    at Object.open (/Users/liepajan/.atom/packages/coffee-compile/lib/main.coffee:95:20)
    at Object.display (/Users/liepajan/.atom/packages/coffee-compile/lib/main.coffee:68:6)
    at HTMLElement.atom.commands.add.coffee-compile:compile (/Users/liepajan/.atom/packages/coffee-compile/lib/main.coffee:20:71)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)

  | PreviewEditor | @ | preview-editor.coffee [sm]:12
-- | -- | -- | --
  | (anonymous) | @ | main.coffee [sm]:46
  | createItemForURI | @ | <embedded>:28750
  | (anonymous) | @ | <embedded>:28556
  | step | @ | <embedded>:27437
  | (anonymous) | @ | <embedded>:27437
  | (anonymous) | @ | <embedded>:27437
  | openURIInPane | @ | <embedded>:28734
  | open | @ | main.coffee [sm]:95
  | display | @ | main.coffee [sm]:68
  | atom.commands.add.coffee-compile:compile | @ | main.coffee [sm]:20
  | handleCommandEvent | @ | <embedded>:23518
  | module.exports.KeymapManager.dispatchCommandEvent | @ | <embedded>:69869
  | module.exports.KeymapManager.handleKeyboardEvent | @ | <embedded>:69660
  | handleDocumentKeyEvent | @ | <embedded>:19404

**Comment by davidhaimson** [comment]
I'm also seeing this, Mac OS 10.13.2, Atom 1.23.1, coffee-compile 0.28.1. This bug makes coffee-compile completely useless, so I am hoping this gets developer attention soon!

**Comment by adrianlee44** [comment]
Thanks for reporting this. It seems like the latest Atom bumped coffee-script version and broke coffee-compile. I converted some of coffee-compile code to Javascript and it's working properly now with 0.29.0.
