### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by jwerre** [adrianlee44/atom-coffee-compile#53]
The following error occurs when compiling:

Uncaught (in promise) TypeError: Class constructor TextEditor cannot be invoked without 'new'
    at new PreviewEditor (/Users/jw/.atom/packages/coffee-compile/lib/preview-editor.coffee:12:5)
    at /Users/jw/.atom/packages/coffee-compile/lib/main.coffee:46:11
    at Workspace.createItemForURI (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1324:28)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1130:42)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:449
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:105)
    at Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1308:25)
    at Object.open (/Users/jw/.atom/packages/coffee-compile/lib/main.coffee:95:20)
    at Object.display (/Users/jw/.atom/packages/coffee-compile/lib/main.coffee:68:6)
    at HTMLElement.atom.commands.add.coffee-compile:compile (/Users/jw/.atom/packages/coffee-compile/lib/main.coffee:20:71)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)

Atom: v1.23.1
Coffee-Compiler: v0.28.1

**Comment by adrianlee44** [comment]
This should be fixed with v0.29.0. See #52 for additional information.

**Comment by jwerre** [comment]
This is still happening in version 0.29.0
